[project]
name = "ubo-morph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ndido98", email = "ndido98@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0.0,<2.5.0",
    "opencv-contrib-python>=5.0.0.93",
    "pandas>=3.0.3",
    "tqdm>=4.68.4",
]

[project.scripts]
ubo-morph = "ubo_morph.cli:main"

[project.optional-dependencies]
dlib = [
    "dlib>=20.0.1",
]
gpu = [
    "numba>=0.66",
]
mediapipe = [
    "mediapipe>=0.10.35",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.15.21",
    "ty>=0.0.59",
]
